# Generated by Django 4.0.2 on 2022-03-05 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PressRelease',
            fields=[
                ('PressReleaseId', models.AutoField(primary_key=True, serialize=False)),
                ('PressReleaseTitle', models.CharField(max_length=64)),
                ('PressReleaseDate', models.DateField()),
                ('PressReleaseMinistry', models.CharField(max_length=64)),
                ('PressReleaseLink', models.CharField(max_length=200)),
                ('PressReleaseSummary', models.CharField(max_length=255)),
            ],
        ),
    ]
