# Generated by Django 4.0.2 on 2022-03-05 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TLDR', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pressrelease',
            name='PressReleaseSummary',
            field=models.TextField(),
        ),
    ]
