# Generated by Django 4.0.2 on 2022-03-06 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TLDR', '0002_alter_pressrelease_pressreleasesummary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PressRelease',
        ),
    ]
